packaging:
  - _packaging/**/*
translation:
  - po/*
documentation:
  - docs/**/*
  - '*.md'
chore:
  - .flake8
python:
  - gaphor/**/*.py
skip-changelog:
  - .pre-commit-config.yaml
  - .all-contributorsrc
